hydra:
  run:
    dir: ${run.outputs_root}/${data.qid}/${hydra.job.override_dirname}/${al.sampler.name}/seed=${run.seed}
  sweep:
    dir: .
    subdir: ${run.outputs_root}/${data.qid}/${hydra.job.override_dirname}/${al.sampler.name}/seed=${run.seed}
  launcher:
    _target_: hydra._internal.core_plugins.basic_launcher.BasicLauncher
  sweeper:
    _target_: hydra._internal.core_plugins.basic_sweeper.BasicSweeper
    max_batch_size: null
    params: null
  help:
    app_name: ${hydra.job.name}
    header: '${hydra.help.app_name} is powered by Hydra.

      '
    footer: 'Powered by Hydra (https://hydra.cc)

      Use --hydra-help to view Hydra specific help

      '
    template: '${hydra.help.header}

      == Configuration groups ==

      Compose your configuration from those groups (group=option)


      $APP_CONFIG_GROUPS


      == Config ==

      Override anything in the config (foo.bar=value)


      $CONFIG


      ${hydra.help.footer}

      '
  hydra_help:
    template: 'Hydra (${hydra.runtime.version})

      See https://hydra.cc for more info.


      == Flags ==

      $FLAGS_HELP


      == Configuration groups ==

      Compose your configuration from those groups (For example, append hydra/job_logging=disabled
      to command line)


      $HYDRA_CONFIG_GROUPS


      Use ''--cfg hydra'' to Show the Hydra config.

      '
    hydra_help: ???
  hydra_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][HYDRA] %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
    root:
      level: INFO
      handlers:
      - console
    loggers:
      logging_example:
        level: DEBUG
    disable_existing_loggers: false
  job_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][%(name)s][%(levelname)s] - %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
      file:
        class: logging.FileHandler
        formatter: simple
        filename: ${hydra.runtime.output_dir}/${hydra.job.name}.log
    root:
      level: INFO
      handlers:
      - console
      - file
    disable_existing_loggers: false
  env: {}
  mode: MULTIRUN
  searchpath: []
  callbacks: {}
  output_subdir: .hydra
  overrides:
    hydra:
    - hydra.mode=MULTIRUN
    task:
    - run.on_exist=skip
    - split.n_train=50
    - al.budget=50
    - train.epochs=1
    - al.rounds=3
    - al/sampler=msp
  job:
    name: main
    chdir: null
    override_dirname: al.budget=50,al.rounds=3,split.n_train=50,train.epochs=1
    id: ???
    num: ???
    config_name: config
    env_set: {}
    env_copy: []
    config:
      override_dirname:
        kv_sep: '='
        item_sep: ','
        exclude_keys:
        - run.seed
        - data.qid
        - al.sampler.name
        - al/sampler
        - run
        - train
        - model
        - al
        - infer
        - data
        - split
        - confidence
        - gate
        - cleaner
        - task
        - dataset
        - run.on_exist
        - run.out_dir
        - run.data_dir
  runtime:
    version: 1.3.2
    version_base: '1.3'
    cwd: /home/esakit25/work/tensaku
    config_sources:
    - path: hydra.conf
      schema: pkg
      provider: hydra
    - path: /home/esakit25/work/tensaku/configs
      schema: file
      provider: main
    - path: ''
      schema: structured
      provider: schema
    output_dir: ???
    choices:
      task: sas
      cleaner: base
      run: base
      gate: default
      confidence: default
      split: standard
      data: base
      infer: base
      train: standard
      model: bert
      al: base
      al/sampler: msp
      qid: Y14_1-2_1_3
      hydra/env: default
      hydra/callbacks: null
      hydra/job_logging: default
      hydra/hydra_logging: default
      hydra/hydra_help: default
      hydra/help: default
      hydra/sweeper: basic
      hydra/launcher: basic
      hydra/output: default
  verbose: false
job_logging:
  root:
    level: INFO
  handlers:
    file:
      filename: main.log
    console:
      format: '[%(asctime)s][%(name)s][%(levelname)s] - %(message)s'
qid:
  value: Y14_1-2_1_3
al:
  sampler:
    name: msp
    conf_key: msp
  rounds: 3
  budget: 50
  stop_when_pool_empty: true
  seed:
    run.seed: null
model:
  name: cl-tohoku/bert-base-japanese-v3
  speed: full
  num_labels: 15
  ckpt: null
  freeze_base: false
  dropout: 0.1
train:
  lr_full: 2.0e-05
  epochs: 1
  batch_size: 16
  weight_decay: 0.01
  warmup_ratio: 0.06
  max_grad_norm: 1.0
  early_stopping: true
  patience: 8
infer:
  ckpt: null
  trust: false
  batch_size: 32
  device: auto
data:
  qid: ${qid.value}
  data_root: data_sas
  split_dir: splits
  base_dir: ${run.data_dir}
  input_all: /home/esakit25/work/tensaku/data_sas/all.jsonl
  files:
    labeled: labeled.jsonl
    dev: dev.jsonl
    test: test.jsonl
    pool: pool.jsonl
  text_key_primary: mecab
  label_key: score
  id_key: id
  max_len: 128
split:
  label_key: score
  seed: ${run.seed}
  stratify: true
  mode: n_train
  n_train: 50
  ratio:
    test: 0.15
    dev: 0.15
confidence:
  estimators:
  - name: msp
    higher_is_better: true
    cfg:
      temperature: 1.0
  - name: entropy
    higher_is_better: true
    cfg:
      temperature: 1.0
  - name: margin
    higher_is_better: true
    cfg:
      temperature: 1.0
  - name: energy
    higher_is_better: true
    cfg:
      temperature: 1.0
  - name: trust
    higher_is_better: true
    cfg:
      version: v2
      metric: cosine
      k_list:
      - 5
      agg: median
      trim_q: 0.1
      normalize: zscore
gate:
  mode: compare
  estimators:
  - name: msp
    higher_is_better: true
  - name: entropy
    higher_is_better: false
  - name: trust
    higher_is_better: true
  eps_cse: 0.05
  cse_abs_err: 2
run:
  seed: 42
  on_exist: skip
  save_logits: true
  save_predictions: true
  outputs_root: outputs
  data_dir: ${hydra:runtime.cwd}/${data.data_root}/q-${data.qid}/base_split
  out_dir: ${hydra:runtime.output_dir}
cleaner:
  round_end:
    enabled: true
    kinds:
    - array
    - logit
    - emb
    - prob
    - ckpt
  experiment_end:
    enabled: false
    kinds: []
task:
  name: sas_total_score
