hydra:
  run:
    dir: outputs/${data.qid}/single_run/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: .
    subdir: outputs/${data.qid}/${hydra.job.override_dirname}/${al.sampler.name}/seed=${run.seed}
  launcher:
    _target_: hydra._internal.core_plugins.basic_launcher.BasicLauncher
  sweeper:
    _target_: hydra._internal.core_plugins.basic_sweeper.BasicSweeper
    max_batch_size: null
    params: null
  help:
    app_name: ${hydra.job.name}
    header: '${hydra.help.app_name} is powered by Hydra.

      '
    footer: 'Powered by Hydra (https://hydra.cc)

      Use --hydra-help to view Hydra specific help

      '
    template: '${hydra.help.header}

      == Configuration groups ==

      Compose your configuration from those groups (group=option)


      $APP_CONFIG_GROUPS


      == Config ==

      Override anything in the config (foo.bar=value)


      $CONFIG


      ${hydra.help.footer}

      '
  hydra_help:
    template: 'Hydra (${hydra.runtime.version})

      See https://hydra.cc for more info.


      == Flags ==

      $FLAGS_HELP


      == Configuration groups ==

      Compose your configuration from those groups (For example, append hydra/job_logging=disabled
      to command line)


      $HYDRA_CONFIG_GROUPS


      Use ''--cfg hydra'' to Show the Hydra config.

      '
    hydra_help: ???
  hydra_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][HYDRA] %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
    root:
      level: INFO
      handlers:
      - console
    loggers:
      logging_example:
        level: DEBUG
    disable_existing_loggers: false
  job_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][%(name)s][%(levelname)s] - %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
      file:
        class: logging.FileHandler
        formatter: simple
        filename: ${hydra.runtime.output_dir}/${hydra.job.name}.log
    root:
      level: INFO
      handlers:
      - console
      - file
    disable_existing_loggers: false
  env: {}
  mode: MULTIRUN
  searchpath: []
  callbacks: {}
  output_subdir: config
  overrides:
    hydra:
    - hydra.mode=MULTIRUN
    task:
    - data.qid=Y14_1-2_1_3
    - al/sampler=random,kmeans,trust,msp,hybrid
    - run.seed=42,43
    - al.budget=10,50,100
    - run.on_exist=overwrite
  job:
    name: main
    chdir: true
    override_dirname: al.budget=10,50,100
    id: ???
    num: ???
    config_name: config
    env_set: {}
    env_copy: []
    config:
      override_dirname:
        kv_sep: '='
        item_sep: ','
        exclude_keys:
        - run.seed
        - data.qid
        - run.on_exist
        - run.out_dir
        - run.data_dir
        - al/sampler
        - al.sampler.name
  runtime:
    version: 1.3.2
    version_base: '1.3'
    cwd: /home/esakit25/work/tensaku
    config_sources:
    - path: hydra.conf
      schema: pkg
      provider: hydra
    - path: /home/esakit25/work/tensaku/configs
      schema: file
      provider: main
    - path: ''
      schema: structured
      provider: schema
    output_dir: ???
    choices:
      task: sas
      cleanup: base
      run: base
      gate: default
      confidence: default
      split: standard
      data: base
      infer: base
      train: standard
      model: bert
      al: base
      al/sampler: random
      hydra/env: default
      hydra/callbacks: null
      hydra/job_logging: default
      hydra/hydra_logging: default
      hydra/hydra_help: default
      hydra/help: default
      hydra/sweeper: basic
      hydra/launcher: basic
      hydra/output: default
  verbose: false
al:
  sampler:
    name: random
  rounds: 30
  budget: 50
  stop_when_pool_empty: true
  seed: 42
model:
  name: cl-tohoku/bert-base-japanese-v3
  speed: full
  num_labels: 15
  ckpt: null
train:
  epochs: 20
  batch_size: 16
  lr_full: 2.0e-05
  lr_frozen: 0.0005
  patience: 3
infer:
  ckpt: null
  trust: false
  batch_size: 32
data:
  qid: Y14_1-2_1_3
  base_dir: data_sas/splits/${.qid}
  input_all: data_sas/all.jsonl
  files:
    labeled: labeled.jsonl
    dev: dev.jsonl
    test: test.jsonl
    pool: pool.jsonl
  text_key_primary: mecab
  label_key: score
  id_key: id
  max_len: 128
split:
  label_key: score
  seed: ${run.seed}
  stratify: true
  mode: n_train
  n_train: 50
  ratio:
    test: 0.15
    dev: 0.15
confidence:
  estimators:
  - name: msp
  - name: entropy
  - name: trust
    version: v2
    metric: cosine
    k_list:
    - 5
    agg: median
    trim_q: 0.1
    normalize: zscore
gate:
  conf_key: trust
  eps_cse: 0.05
  cse_abs_err: 2
run:
  seed: 42
  on_exist: overwrite
  save_logits: true
  save_predictiions: true
  data_dir: null
  out_dir: null
cleanup:
  immediate:
    checkpoints: true
    temp_data: true
  delayed:
    infer_arrays: true
    arrays: true
  post_experiment:
    all_checkpoints: false
    infer_arrays: true
    temp_dirs: true
task:
  name: sas_total_score
